plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.13'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.payments'
version = '0.0.1-SNAPSHOT'
description = 'payment-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

configurations.configureEach {
    exclude group: "org.springframework.boot", module: "spring-boot-starter-logging"
}

dependencies {

    implementation name: 'java-wrapper', version: '1.2'

    implementation('org.springframework.boot:spring-boot-starter-web') {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
    }

    implementation 'org.springframework.boot:spring-boot-starter-log4j2'

    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.json:json:20230618'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'net.datafaker:datafaker:1.8.0'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.80'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}