rootLogger.level = info
#logger.payments.name = com.payments
#logger.payments.level = debug
logger.gateway.name=com.gateway
logger.gateway.level=debug
#logger.gateway.appenderRef.console.ref=consoleLogger
property.filename=payment-service.log
property.maxFileAge=365
appender.reportingLog.type=RollingFile
appender.reportingLog.name=File
appender.reportingLog.fileName=/home/ashish/logs/${filename}
appender.reportingLog.filePattern=/home/ashish/logs/${filename}.%d{yyyy-MM-dd}
appender.reportingLog.layout.type=PatternLayout
appender.reportingLog.layout.pattern=[$${env:HOSTNAME}] - %5p [%d][%t](%F:%L) - [%X{X-Correlation-Id}][%X{X-Auth-User}][%X{X-User-Action}]  %m%n
appender.reportingLog.policies.type=TimeBasedTriggeringPolicy
appender.reportingLog.policies.interval=1
appender.reportingLog.strategy.type=DefaultRolloverStrategy
appender.reportingLog.strategy.action.type=Delete
appender.reportingLog.strategy.action.basepath=/home/ashish/logs/
appender.reportingLog.strategy.action.maxdepth=2
appender.reportingLog.strategy.action.condition.type=IfLastModified
appender.reportingLog.strategy.action.condition.age=${maxFileAge}D
appender.reportingLog.strategy.action.PathConditions.type=IfFileName
appender.reportingLog.strategy.action.PathConditions.glob=${filename}.*
appender.reportingLog.append=true
rootLogger.includeLocation=true
rootLogger.appenderRefs=reportingLog, consoleRef
rootLogger.appenderRef.reportingLog.ref=File
rootLogger.appenderRef.consoleRef.ref=consoleLogger
appender.consoleRef.type=Console
appender.consoleRef.name=consoleLogger
appender.consoleRef.layout.type=PatternLayout
appender.consoleRef.layout.pattern=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%t] - %c{1}:%L - %msg%n