package com.payments.enums;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public enum ChargebackReason {

    // Mastercard
    TRANSACTION_NOT_RECOGNIZED("75"),
    FRAUDULENT_MULTIPLE_TRANSACTIONS("57"),
    COUNTERFEIT_TRANSACTION("62"),
    FRAUD_CARD_PRESENT_ENVIRONMENT("81"),
    FRAUD_CARD_ABSENT_ENVIRONMENT("83"),
    DECLINED_AUTHORIZATION("71"),
    NO_AUTHORIZATION("72"),
    EXPIRED_CARD("73"),
    LATE_PRESENTMENT("74"),
    INCORRECT_CURRENCY_OR_TRANSACTION_CODE_OR_DOMESTIC_TRANSACTION_VIOLATION("76"),
    NON_MATCHING_ACCOUNT_NUMBER("77"),
    INCORRECT_TRANSACTION_AMOUNT_OR_INCORRECT_ACCOUNT_NUMBER("80"),
    DUPLICATE_PROCESSING("82"),
    PAID_BY_OTHER_MEANS("86"),
    CANCELLED_RECURRING_TRANSACTION("41"),
    NOT_AS_DESCRIBED_OR_DEFECTIVE_MERCHANDISE("53"),
    CREDIT_NOT_PROCESSED("85"),
    SERVICE_NOT_PROVIDED_OR_MERCHANDISE_NOT_RECEIVED("30"),

    REQUESTED_REQUIRED_INFORMATION_ILLEGIBLE_OR_MISSING("4802"),
    AUTHORIZATION_RELATED_CHARGEBACK("4808"),
    WARNING_BULLETIN_FILE("4807"),
    TRANSACTION_AMOUNT_DIFFERS("4831"),
    POINT_OF_INTERACTION_ERROR("4834"),
    NO_CARDHOLDER_AUTHORIZATION("4837"),
    FRAUDULENT_PROCESSING_OF_TRANSACTIONS("4840"),
    LATE_PRESENTMENT_MC("4842"),
    CORRECT_TRANSACTION_CURRENCY_CODE_NOT_PROVIDED("4846"),
    QUESTIONABLE_MERCHANT_ACTIVITY("4849"),
    INSTALLMENT_BILLING_DISPUTE("4850"),
    CHIP_LIABILITY_SHIFT("4870"),
    CHIP_PIN_LIABILITY_SHIFT_LOST_STOLEN_NRI_FRAUD("4871"),
    CANCELED_RECURRING_OR_DIGITAL_GOODS_TRANSACTIONS("4841"),
    CARDHOLDER_DISPUTES("4853"),
    CARDHOLDER_DISPUTE_NOT_CLASSIFIED_ELSEWHERE("4854"),
    GOODS_OR_SERVICES_NOT_PROVIDED("4855"),
    ACCOUNT_NUMBER_NOT_ON_FILE("4812"),
    NO_SHOW_ADDENDUM_ATM_DISPUTE("4859"),
    CREDIT_NOT_PROCESSED_MC("4860"),
    CARDHOLDER_DOES_NOT_RECOGNIZE_POTENTIAL_FRAUD("4863"),
    DOMESTIC_CHARGEBACK_DISPUTE_EUROPE_REGION_ONLY("4999"),

    // Visa
    EMV_LIABILITY_SHIFT_COUNTERFEIT_FRAUD("10.1"),
    EMV_LIABILITY_SHIFT_NON_COUNTERFEIT_FRAUD("10.2"),
    OTHER_FRAUD_CARD_PRESENT_ENVIRONMENT("10.3"),
    OTHER_FRAUD_CARD_ABSENT_ENVIRONMENT("10.4"),
    VISA_FRAUD_MONITORING_PROGRAM("10.5"),
    CARD_RECOVERY_BULLETIN("11.1"),
    DECLINED_AUTHORIZATION_VISA("11.2"),
    NO_AUTHORIZATION_VISA("11.3"),
    LATE_PRESENTMENT_VISA("12.1"),
    INCORRECT_TRANSACTION_CODE("12.2"),
    INCORRECT_CURRENCY("12.3"),
    INCORRECT_ACCOUNT_NUMBER("12.4"),
    INCORRECT_AMOUNT("12.5"),
    DUPLICATE_PROCESSING_PAID_BY_OTHER_MEANS("12.6"),
    DUPLICATE_PROCESSING_VISA("12.6.1"),
    PAID_BY_OTHER_MEANS_VISA("12.6.2"),
    INVALID_DATA("12.7"),
    MERCHANDISE_SERVICES_NOT_RECEIVED("13.1"),
    CANCELED_RECURRING_TRANSACTION_VISA("13.2"),
    NOT_AS_DESCRIBED_OR_DEFECTIVE_MERCHANDISE_SERVICES("13.3"),
    COUNTERFEIT_MERCHANDISE("13.4"),
    MISREPRESENTATION("13.5"),
    CREDIT_NOT_PROCESSED_VISA("13.6"),
    CANCELLED_MERCHANDISE_SERVICES("13.7"),
    ORIGINAL_CREDIT_TRANSACTION_NOT_ACCEPTED("13.8"),
    NON_RECEIPT_OF_CASH_OR_LOAD_TRANSACTION_VALUE("13.9"),

    // Amex
    CHARGE_AMOUNT_EXCEEDS_AUTHORIZATION_AMOUNT("A01"),
    NO_VALID_AUTHORIZATION("A02"),
    AUTHORIZATION_APPROVAL_EXPIRED("A08"),
    CREDIT_NOT_PROCESSED_AMEX("C02"),
    GOODS_SERVICES_RETURNED_OR_REFUSED("C04"),
    GOODS_SERVICES_CANCELED("C05"),
    GOODS_SERVICES_NOT_RECEIVED_OR_ONLY_PARTIALLY_RECEIVED("C08"),
    PAID_BY_OTHER_MEANS_AMEX("C14"),
    NO_SHOW_OR_CAR_DEPOSIT_CANCELED("C18"),
    CANCELED_RECURRING_BILLING("C28"),
    GOODS_SERVICES_NOT_AS_DESCRIBED("C31"),
    GOODS_SERVICES_DAMAGED_OR_DEFECTIVE("C32"),
    VEHICLE_RENTAL_CAPITAL_DAMAGES("M10"),
    VEHICLE_RENTAL_THEFT_OR_LOSS_OF_USE("M49"),
    FRAUD_FULL_RECOURSE_PROGRAM("FR2"),
    IMMEDIATE_CHARGEBACK_PROGRAM("FR4"),
    PARTIAL_IMMEDIATE_CHARGEBACK_PROGRAM("FR6"),
    MISSING_IMPRINT("F10"),
    MISSING_SIGNATURE("F14"),
    NO_CARDMEMBER_AUTHORIZATION("F24"),
    CARD_NOT_PRESENT("F29"),
    EMV_COUNTERFEIT("F30"),
    EMV_LIST_STOLEN_NON_RECEIVED("F31"),
    INSUFFICIENT_REPLY("R03"),
    NO_REPLY("R13"),
    CHARGEBACK_AUTHORIZATION("M01"),
    UNASSIGNED_CARD_NUMBER("P01"),
    CREDIT_PROCESSED_AS_CHARGE("P03"),
    CHARGE_PROCESSED_AS_CREDIT("P04"),
    INCORRECT_CHARGE_AMOUNT("P05"),
    LATE_SUBMISSION("P07"),
    DUPLICATE_CHARGE("P08"),
    NON_MATCHING_CARD_NUMBER("P22"),
    CURRENCY_DISCREPANCY("P23"),

    // Discover
    GOOD_FAITH_INVESTIGATION("05"),
    CARDHOLDER_DOES_NOT_RECOGNIZE("AA"),
    CANCELED_RECURRING_TRANSACTION_DISCOVER("AP"),
    ALTERED_AMOUNT("AW"),
    CREDIT_POSTED_AS_CARD_SALE("CD"),
    DISPUTE_COMPLIANCE("DC"),
    DUPLICATE_PROCESSING_DISCOVER("DP"),
    ILLEGIBLE_SALES_DATA("IC"),
    NON_RECEIPT_OF_CASH_FROM_ATM("NF"),
    PAID_BY_OTHER_MEANS_DISCOVER("PM"),
    NON_RECEIPT_OF_GOODS_OR_SERVICES("RG"),
    QUALITY_DISCREPANCY("RM"),
    CREDIT_NOT_RECEIVED("RN2"),
    AUTHORIZATION_NON_COMPLIANCE("AT"),
    DECLINED_AUTHORIZATION_DISCOVER("DA"),
    EXPIRED_CARD_DISCOVER("EX"),
    NO_AUTHORIZATION_DISCOVER("NA"),
    INVALID_CARD_NUMBER("IN"),
    LATE_PRESENTMENT_DISCOVER("LP"),
    NOT_CLASSIFIED("NC"),
    FRAUD_CARD_PRESENT_ENVIRONMENT_DISCOVER("UA01"),
    FRAUD_CARD_NOT_PRESENT_ENVIRONMENT("UA02"),
    FRAUD_COUNTERFEIT_CHIP_TRANSACTION("UA05"),
    FRAUD_CHIP_AND_PIN_TRANSACTION("UA06"),
    REQUEST_TRANSACTION_RECEIPT("UA10"),
    CARDHOLDER_CLAIMS_FRAUD("UA11");

    private final String code;

    private static final Map<String, ChargebackReason> LOOKUP = new HashMap<>();

    static {
        for (ChargebackReason reason : values()) {
            LOOKUP.put(reason.code, reason);
        }
    }

    ChargebackReason(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public static ChargebackReason fromCode(String code) {
        return LOOKUP.get(code);
    }

    public static final List<ChargebackReason> VISA_REASONS = List.of(
            EMV_LIABILITY_SHIFT_COUNTERFEIT_FRAUD,
            EMV_LIABILITY_SHIFT_NON_COUNTERFEIT_FRAUD,
            OTHER_FRAUD_CARD_PRESENT_ENVIRONMENT,
            OTHER_FRAUD_CARD_ABSENT_ENVIRONMENT,
            VISA_FRAUD_MONITORING_PROGRAM,
            CARD_RECOVERY_BULLETIN,
            DECLINED_AUTHORIZATION_VISA,
            NO_AUTHORIZATION_VISA,
            LATE_PRESENTMENT_VISA,
            INCORRECT_TRANSACTION_CODE,
            INCORRECT_CURRENCY,
            INCORRECT_ACCOUNT_NUMBER,
            INCORRECT_AMOUNT,
            DUPLICATE_PROCESSING_PAID_BY_OTHER_MEANS,
            DUPLICATE_PROCESSING_VISA,
            PAID_BY_OTHER_MEANS_VISA,
            INVALID_DATA,
            MERCHANDISE_SERVICES_NOT_RECEIVED,
            CANCELED_RECURRING_TRANSACTION_VISA,
            NOT_AS_DESCRIBED_OR_DEFECTIVE_MERCHANDISE_SERVICES,
            COUNTERFEIT_MERCHANDISE,
            MISREPRESENTATION,
            CREDIT_NOT_PROCESSED_VISA,
            CANCELLED_MERCHANDISE_SERVICES,
            ORIGINAL_CREDIT_TRANSACTION_NOT_ACCEPTED,
            NON_RECEIPT_OF_CASH_OR_LOAD_TRANSACTION_VALUE
    );

    public static final List<ChargebackReason> MASTERCARD_REASONS = List.of(
            TRANSACTION_NOT_RECOGNIZED,
            FRAUDULENT_MULTIPLE_TRANSACTIONS,
            COUNTERFEIT_TRANSACTION,
            FRAUD_CARD_PRESENT_ENVIRONMENT,
            FRAUD_CARD_ABSENT_ENVIRONMENT,
            DECLINED_AUTHORIZATION,
            NO_AUTHORIZATION,
            EXPIRED_CARD,
            LATE_PRESENTMENT,
            INCORRECT_CURRENCY_OR_TRANSACTION_CODE_OR_DOMESTIC_TRANSACTION_VIOLATION,
            NON_MATCHING_ACCOUNT_NUMBER,
            INCORRECT_TRANSACTION_AMOUNT_OR_INCORRECT_ACCOUNT_NUMBER,
            DUPLICATE_PROCESSING,
            PAID_BY_OTHER_MEANS,
            CANCELLED_RECURRING_TRANSACTION,
            NOT_AS_DESCRIBED_OR_DEFECTIVE_MERCHANDISE,
            CREDIT_NOT_PROCESSED,
            SERVICE_NOT_PROVIDED_OR_MERCHANDISE_NOT_RECEIVED,
            REQUESTED_REQUIRED_INFORMATION_ILLEGIBLE_OR_MISSING,
            AUTHORIZATION_RELATED_CHARGEBACK,
            WARNING_BULLETIN_FILE,
            TRANSACTION_AMOUNT_DIFFERS,
            POINT_OF_INTERACTION_ERROR,
            NO_CARDHOLDER_AUTHORIZATION,
            FRAUDULENT_PROCESSING_OF_TRANSACTIONS,
            LATE_PRESENTMENT_MC,
            CORRECT_TRANSACTION_CURRENCY_CODE_NOT_PROVIDED,
            QUESTIONABLE_MERCHANT_ACTIVITY,
            INSTALLMENT_BILLING_DISPUTE,
            CHIP_LIABILITY_SHIFT,
            CHIP_PIN_LIABILITY_SHIFT_LOST_STOLEN_NRI_FRAUD,
            CANCELED_RECURRING_OR_DIGITAL_GOODS_TRANSACTIONS,
            CARDHOLDER_DISPUTES,
            CARDHOLDER_DISPUTE_NOT_CLASSIFIED_ELSEWHERE,
            GOODS_OR_SERVICES_NOT_PROVIDED,
            ACCOUNT_NUMBER_NOT_ON_FILE,
            NO_SHOW_ADDENDUM_ATM_DISPUTE,
            CREDIT_NOT_PROCESSED_MC,
            CARDHOLDER_DOES_NOT_RECOGNIZE_POTENTIAL_FRAUD,
            DOMESTIC_CHARGEBACK_DISPUTE_EUROPE_REGION_ONLY
    );
}